# Generated by Django 5.1.4 on 2025-07-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiom_activos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='nombre',
        ),
    ]
