# Generated by Django 5.1.4 on 2025-06-30 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioGenerico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('contrasenya', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('usuariogenerico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.usuariogenerico')),
                ('codigo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsable de los activos',
            },
            bases=('usuarios.usuariogenerico',),
        ),
    ]
